<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Description>A high-performance framework for the Valve Data Format, also called KeyValues.</Description>
    <Copyright>Copyright © Shravan Rajinikanth 2016</Copyright>
    <Company>Gameloop</Company>
    <Authors>Shravan Rajinikanth</Authors>
    <Version>0.7</Version>
    <AssemblyVersion>0.7.0.0</AssemblyVersion>
    <FileVersion>0.7.0.0</FileVersion>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>Vdf.NET</Title>
    <PackageId>Gameloop.Vdf</PackageId>
    <PackageTags>vdf keyvalues steam</PackageTags>
    <RepositoryUrl>https://github.com/shravan2x/Gameloop.Vdf</RepositoryUrl>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageProjectUrl>https://github.com/shravan2x/Gameloop.Vdf</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DefineConstants>RELEASE</DefineConstants>
    <NoWarn>1591;1701;1702;1705</NoWarn>
    <Optimize>true</Optimize>
  </PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Gameloop.Vdf.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
</Project>